import React, { useState } from "react";
import { BreadCrumb, ReferandEarnCard } from "../../../components";
import styled from "styled-components";
import { AiOutlineMinus, AiOutlinePlus } from "react-icons/ai";

// Styled component for Wrapper
const Wrapper = styled.div`
  .faq-item:last-child {
    border-bottom: none; /* Remove border from the last item in each column */
  }

  .faq-answer {
    padding: 0.25rem; /* Adjust padding for answer section */
    background: #ffffff; /* White background for the answer */
    color: #333333; /* Dark text color for readability */
    border: 1px solid #e5e7eb; /* Gray border */
    border-top: none; /* Remove top border to avoid double borders */
    transition: max-height 0.3s ease, opacity 0.3s ease; /* Smooth transition */
    line-height: 1.6;
    max-height: 0;
    opacity: 0;
    overflow: hidden;
    text-align: justify; /* Justify text */
    margin-bottom: 0.25rem; /* Add margin only to the bottom */
  }

  .faq-answer.open {
    max-height: 200px; /* Adjust as needed based on content length */
    opacity: 1;
    padding: 1rem;
    border-radius: 0 0 8px 8px; /* Rounded corners only at the bottom */
    border-top: 1px solid #e5e7eb; /* Gray border */
    margin-bottom: 1rem; /* Add margin only to the bottom */
  }
`;

const FAQ = () => {
  const breadcrumbs = [
    { label: "Home", href: "/dashboard" },
    { label: "FAQ", href: "/dashboard/refer-earn" },
  ];
  const [openIndex, setOpenIndex] = useState(null);

  const toggleAccordion = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "What is a cryptocurrency faucet?",
      answer:
        "A cryptocurrency faucet is a platform that allows users to earn small amounts of cryptocurrency by completing tasks such as solving captchas, clicking on links, or participating in other activities. It's a way for users to get started with cryptocurrency without needing to make a financial investment.",
    },
    {
      question: "How can I earn crypto on this website?",
      answer:
        "You can earn cryptocurrency by completing various tasks including solving captchas, participating in faucets, clicking on shortlinks, and performing daily tasks. Additionally, you can earn referral commissions for every user you refer to the platform.",
    },
    {
      question: "What are the bonuses available on this platform?",
      answer:
        "Our platform offers several bonuses including a loyalty bonus for daily logins, referral bonuses for inviting new users, and task bonuses for completing daily activities. The loyalty bonus can increase up to 100% based on your daily logins.",
    },
    {
      question: "How do I withdraw my earnings?",
      answer:
        "You can withdraw your earnings via the 'Withdraw' tab using instant payment gateways such as FaucetPay, ExpressCrypto, or Coinbase. Simply choose your preferred gateway and follow the instructions to complete the withdrawal process.",
    },
    {
      question: "What should I do if I need help?",
      answer:
        "If you need assistance, you can use our live chat support to raise a ticket. Our support team is available to help you with any issues or questions you may have regarding the platform.",
    },
    {
      question: "How does the referral system work?",
      answer:
        "Our referral system allows you to earn commissions by referring new users to the platform. You'll receive a percentage of the earnings generated by your referrals, providing you with an additional income stream.",
    },
    {
      question: "What is the loyalty bonus?",
      answer:
        "The loyalty bonus is a reward for logging in daily. You earn a 1% bonus for each consecutive day you log in, with the bonus amount accumulating up to a maximum of 100%.",
    },
    {
      question: "Can I use multiple payment gateways for withdrawals?",
      answer:
        "Yes, you can choose from multiple payment gateways for your withdrawals, including FaucetPay, ExpressCrypto, and Coinbase. Select the one that suits you best and follow the provided instructions.",
    },
  ];

  // Split faqs into two arrays for the two columns
  const firstColumnFaqs = faqs.slice(0, 4);
  const secondColumnFaqs = faqs.slice(4);

  return (
    <Wrapper>
      <BreadCrumb title="FAQ" breadcrumbs={breadcrumbs} />
      <div className="flex justify-center mt-8">
        <div className="bg-gray-200 p-4 rounded-lg" style={{ width: '728px', height: '90px' }}>
          Top Ad Space 728×90
        </div>
      </div>

      <div className="mt-8 bg-white rounded-lg p-8">
        
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text">
            Frequently Asked Questions
          </h1>
        </div>
        <hr className="border-gray-300 my-4" />
        <div className="mb-8 text-gray-700">
          <p>
            Find detailed answers to common questions about cryptocurrency
            faucets, earning methods, bonuses, withdrawals, and more. Discover
            how to get started and maximize your experience on our platform.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
          <div className="faq-column">
            {firstColumnFaqs.map((faq, index) => (
              <div key={index} className="faq-item">
                <div
                  className="faq-header bg-gradient-to-r from-blue-500 to-blue-600 text-white px-4 py-2 flex items-center justify-between cursor-pointer hover:from-blue-600 hover:to-blue-700"
                  onClick={() => toggleAccordion(index)}
                >
                  <span>{faq.question}</span>
                  {openIndex === index ? <AiOutlineMinus /> : <AiOutlinePlus />}
                </div>
                <div
                  className={`faq-answer ${openIndex === index ? "open" : ""}`}
                >
                  {faq.answer}
                </div>
              </div>
            ))}
          </div>
          <div className="faq-column">
            {secondColumnFaqs.map((faq, index) => (
              <div key={index} className="faq-item">
                <div
                  className="faq-header bg-gradient-to-r from-blue-500 to-blue-600 text-white px-4 py-2 flex items-center justify-between cursor-pointer hover:from-blue-600 hover:to-blue-700"
                  onClick={() => toggleAccordion(index + 4)} // Adjust index for second column
                >
                  <span>{faq.question}</span>
                  {openIndex === index + 4 ? (
                    <AiOutlineMinus />
                  ) : (
                    <AiOutlinePlus />
                  )}
                </div>
                <div
                  className={`faq-answer ${
                    openIndex === index + 4 ? "open" : ""
                  }`}
                >
                  {faq.answer}
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex justify-center mt-8">
        <div className="bg-gray-200 p-4 rounded-lg" style={{ width: '728px', height: '90px' }}>
          Bottom Ad Space 728×90
        </div>
      </div>
      </div>
    </Wrapper>
  );
};

export default FAQ;
